// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjpDe5qbe-APdpaiM6MqdNJH7kXirr758',
    appId: '1:507426267379:web:a80982e2dd1dceb6b21786',
    messagingSenderId: '507426267379',
    projectId: 'phoneaway-50a5b',
    authDomain: 'phoneaway-50a5b.firebaseapp.com',
    databaseURL: 'https://phoneaway-50a5b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'phoneaway-50a5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_-wnismIgatRgk4PU8xhk4cvfwZYGZEA',
    appId: '1:507426267379:android:d7b235229d82ccfbb21786',
    messagingSenderId: '507426267379',
    projectId: 'phoneaway-50a5b',
    databaseURL: 'https://phoneaway-50a5b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'phoneaway-50a5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAI_f2NQXK7RbvXjLKKFsjoRo7eh8n1oI',
    appId: '1:507426267379:ios:29e605810556fdebb21786',
    messagingSenderId: '507426267379',
    projectId: 'phoneaway-50a5b',
    databaseURL: 'https://phoneaway-50a5b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'phoneaway-50a5b.firebasestorage.app',
    iosBundleId: 'com.example.phoneAway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjpDe5qbe-APdpaiM6MqdNJH7kXirr758',
    appId: '1:507426267379:web:1d64e8c13259c49bb21786',
    messagingSenderId: '507426267379',
    projectId: 'phoneaway-50a5b',
    authDomain: 'phoneaway-50a5b.firebaseapp.com',
    databaseURL: 'https://phoneaway-50a5b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'phoneaway-50a5b.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAI_f2NQXK7RbvXjLKKFsjoRo7eh8n1oI',
    appId: '1:507426267379:ios:763db28d661907d5b21786',
    messagingSenderId: '507426267379',
    projectId: 'phoneaway-50a5b',
    databaseURL: 'https://phoneaway-50a5b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'phoneaway-50a5b.firebasestorage.app',
    iosBundleId: 'com.',
  );

}